### ISSUE TITLE
useFetch: [Feature request] Expose whole the http response on error (in onFetchError)

### ISSUE THREAD

**Issue by red010182** [vueuse/vueuse#1144]
Please consider expose the whole http response in onFetchError.

e.g. ctx.error.response (like axios did)

Currently, there's nothing useful in ctx of onFetchError, I can't even get status code nor url.
It's really hard to customize a useful error handler middleware without key information. 

```
const fetcher = createFetch({
  baseUrl: 'http://localhost:5678/',
  options: {
    async onFetchError(ctx) {
      // only ctx.data and ctx.error
      // can't get status code, request url or request parameters
      console.error(ctx) 
      return ctx
    },
  },
})
```

Feature request:
```
ctx.error.response = { ... } // http response object, contains status code, url, parameters...
```

**Comment by Delicious-Bacon** [comment]
I would like to point out one thing that I noticed.

Like you mentioned, right now, we only have `ctx.data` and `ctx.error` available in the `onFetchError` interceptor, which are not of much use apart from mutating them. I guess that this interceptor is only used for setting default fallbacks to the data.

But the `afterFetch` interceptor has both the `response` and `data` properties in the `ctx` ([source code](https://github.com/vueuse/vueuse/blob/01f8dfbfedf7c3e34fb9871ca3057b1bd905561e/packages/core/useFetch/index.ts#L117)):
```
ctx: {
  response,
  data
}
```
While the `onFetchError` interceptor triggers only on errors, the `afterFetch` interceptor should trigger on any fetch response, even those with error codes, but the documentation only says `The afterFetch option can intercept the response data before it is updated.`  ([Documentation](https://vueuse.org/core/usefetch/#intercepting-a-request))

I would say we're supposed to utilize our handlers in `afterFetch` interceptor since it has the needed information, and it triggers on server responses (the `onFetchError` interceptor triggers whenever there is error, so it would trigger when the server is down, for example).

An example of `afterFetch` interceptor:
```
const fetcher = createFetch({
  // baseUrl: '...',
  options: {
    afterFetch({ response }) {
      const { status, url } = response;

      if (status === 200) {
        console.log('Successfully fetched data @:', url);
      } else if (status === 404) {
        console.log('404 not found @:', url);
      }
    },
  },
  fetchOptions: {
    // ...options
  },
});
```

**Comment by red010182** [comment]
Thanks. This may be a workaround for now. It would be convenient to get response (especially status code and url)  in `onFetchError` for me.

**Comment by wheatjs** [comment]
Going to reopen this as I would like to include it. I'll see if I can get around to it soon
