### ISSUE TITLE
Broken links on Homepage

### ISSUE THREAD

**Issue by jjaimealeman** [vueuse/vueuse#1233]
![Functions](https://i.imgur.com/Gy5BJ1C.png)

![GetStarted](https://i.imgur.com/XqaDHzF.png)

😕

**Comment by antfu** [comment]
I have no problem accessing them. Try refresh the page?

**Comment by okxiaoliang4** [comment]
![image](https://user-images.githubusercontent.com/22525904/153358080-4b813e15-4fb9-4b4e-8ae7-80a170429b09.png)
![image](https://user-images.githubusercontent.com/22525904/153358124-1271c8d8-13e3-4106-803a-638d827fe8ac.png)

The problem is not reproduced. maybe check your network and refresh the page
