### ISSUE TITLE
proposal: useCanvasWebGL()

### ISSUE THREAD

**Issue by michealroberts** [vueuse/vueuse#1425]
### Clear and concise description of the problem

Further to the proposal for useCanvas2D I would like to also implement a useCanvasWebGL() composable which can detect whether to wrap `"webgl"`, `"experimental-webgl"` or `"webgl2"`.

I believe useCanvasWebGL and useCanvas2D should be released as a pair.

### Suggested solution

I'm thinking a proposed solution would look like this:

```vue
<template>
    <canvas ref="canvas"></canvas>
</template>
```

```ts
const canvas = ref<undefined | HTMLCanvasElement>()

const { context } = useCanvasWebGL(canvas, { antialias: false, depth: false })
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wheatjs** [comment]
Wondering about this type for `useCanvas2D` https://github.com/vueuse/vueuse/pull/1373/files#diff-2703575e8917d3cd9f0fd4b826d6c61830bfdb14ef350addb9e29dd59315484cR21 since it includes webgl. Would this be changed? Also would there be a big difference in the return types between this and `useCanvas2D`? If the return types are the same I'm wondering if we should keep this as a single function and switch between 2D and webgl using an option. 

I'd like to know you feedback on this though, maybe my idea is not the best solution here, any thoughts?

**Comment by michael-observerly** [comment]
> Wondering about this type for `useCanvas2D` https://github.com/vueuse/vueuse/pull/1373/files#diff-2703575e8917d3cd9f0fd4b826d6c61830bfdb14ef350addb9e29dd59315484cR21 since it includes webgl. Would this be changed? Also would there be a big difference in the return types between this and `useCanvas2D`? If the return types are the same I'm wondering if we should keep this as a single function and switch between 2D and webgl using an option. 
> 
> 
> 
> I'd like to know you feedback on this though, maybe my idea is not the best solution here, any thoughts? 

Totally understand what you mean. I found the issue with trying to provide a composable for both was slightly tricky as both the types for the return context are different for each I was worried about things being a little spaghettified.

I'm happy to try and work a composable that can accept either webgl or 2d rendering contexts into one uniform composable, as long as nobody sees it as too much of an issue...
