### ISSUE TITLE
A convenient demo block

### ISSUE THREAD

**Issue by gumingWu** [vueuse/vueuse#1586]
### Clear and concise description of the problem

# My Problem
I think the vueuse.org's demo is not easy to view the source code

![image](https://user-images.githubusercontent.com/24989299/167619175-f4d444cd-9f89-4e72-b431-878cdadf43c5.png)

### Suggested solution

# IDEA
Maybe I can supply a new `DemoBlock` that can 
- view the source code intuitively
- provide a copy button, 
- click to github source

E.g.
![image](https://user-images.githubusercontent.com/24989299/167619836-fd91f322-ee87-4c13-80bd-453b5e088da4.png)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I think in VueUse this is different from UI components, where the demo often requires many more lines. Giving we had the usage section below for the minimal usage, I don't think having the code of demo instead of the doc would improve the readability much. Thanks for the proposal, tho I would think to hold it for a while longer.
