### ISSUE TITLE
[useWindowSize] useWindowSize() should return the exact value

### ISSUE THREAD

**Issue by szulcus** [vueuse/vueuse#2486]
### Clear and concise description of the problem

I am getting a value rounded to 1, and I would like to receive the exact value.

### Suggested solution

https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport

### Alternative

Maybe config option?

### Additional context

For now, I must to create my own composable :/

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by syy11cn** [comment]
Hi @szulcus. It seems `window.visualViewport` API also returns integers for `width` and `height` properties.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/57290456/205429327-c562f6e1-1dc6-4295-bdaf-32b577fd0231.png">

Is there any other APIs that could get the accurate value?

**Comment by szulcus** [comment]
@syy11cn for me (Google Chrome user) it works fine 🤔. I don't know any other way, maybe try resize the window very gently. Sometimes an int is returned, sometimes a float.

**Comment by syy11cn** [comment]
@szulcus Yeah, I got it!

When there's a scroll bar, `window.visualViewport.width` returns a value without the width of scroll bar. While `window.innerWidth` (named `width` and returned by `useWindowSize` by default) is a value including the width of scroll bar.

![image](https://user-images.githubusercontent.com/57290456/205433107-40214047-4c10-440f-8ed5-a5ed1cbd21c9.png)

I think an optional config property could be added to obtain the accurate value.

However, I didn't find an API to replace `window.innerWidth` which is able to get layout viewport width and height in double instead of int.

**Comment by szulcus** [comment]
@syy11cn It's possible you're right. In my case, I need the exact height, but I think including the scroll bar information in the documentation did the trick
