### ISSUE TITLE
`useVirtualList` not working in Vue 2

### ISSUE THREAD

**Issue by Ericlm** [vueuse/vueuse#2510]
### Describe the bug

I tried to use `useVirtualList` in a Vue 2 based project, but I couldn't get it working. I copy and pasted the demo into the code but it wasn't working. However, when creating a Vue 3 project, it immediately worked.  

To be more precise, we can see that in the Vue 2 demo that the `margin-top` and `height` of the wrapper div is never updated, and in the DOM inspector the following attribute is visible on the container div : `onscroll="() => { calculateRange(); }"` which probably means that `calculateRange()` is simply never called when using vue 2.

### Reproduction

Vue 2: https://codesandbox.io/s/boring-cache-p9h5li - Vue 3: https://codesandbox.io/s/sleepy-tess-fwu947

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 2.61 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Firefox: 107.0.1
    Safari: 16.1
    Safari Technology Preview: 16.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ErickPetru** [comment]
Hey @Ericlm, I just hit the same problem here with Vue 2.7.

The reasoning is that `useVirtualList` returns the `onScroll` listener as part of the `containerProps`, as we can see [here](https://github.com/vueuse/vueuse/blob/cfcc295261f463c74d80fcb9863cb4bdd7e673b9/packages/core/useVirtualList/index.ts#L75-L81). As the [migration guide describes](https://v3-migration.vuejs.org/breaking-changes/listeners-removed.html#_3-x-syntax), in Vue 3's virtual DOM, event listeners are like any other attributes (just prefixed with `on`), so passing it all through `v-bind` works for Vue 3, since any listener is treated as any other content of `$attrs` object.

But since Vue 2 has a clear separation on what are attributes and what are event listeners, you can bypass the divergent behavior by manually binding each part of the `containerProps` result, like this:

```
<div
  :ref="containerProps.ref"
  :style="containerProps.style"
  @scroll="containerProps.onScroll"
>
  <div v-bind="wrapperProps">
    <div v-for="{ data: item, index} of list" :key="index" style="height: 22px">
      Row: {{ item }}
    </div>
  </div>
</div>
````

Observe that `wrapperProps` contains only `style` inside it (no event listeners involved), so you can keep using v-bind for it if you wish, or even just use `:style="wrapperProps.style"` if you prefer explicit binding everywhere inside your template.

**Comment by Ericlm** [comment]
Works like a charm! 🪄 Thank you very much for your help and your explanation! 😊
