### ISSUE TITLE
Integrate vue-use-sound

### ISSUE THREAD

**Issue by yooneskh** [vueuse/vueuse#256]
Is it possible to integrate [vue-use-sound](https://vuejsexamples.com/a-vue-hook-for-playing-sound-effects/amp/) into vue-use? Or implement something similar? It will become really handy.

**Comment by antfu** [comment]
Looks cool, wanna create an PR for it?

**Comment by yooneskh** [comment]
I would love to, but it is my first time doing it. Do you happen to have a contribution guide?

**Comment by matias-capeletto** [comment]
@yooneskh the contributing guide is here https://github.com/antfu/vueuse/blob/master/CONTRIBUTING.md 👍🏼

**Comment by yooneskh** [comment]
@matias-capeletto thank you. i will look into it and report the progress here.

**Comment by antfu** [comment]
Hi @Tahul, want to ask your opinion about this first. Thanks!

**Comment by Tahul** [comment]
Hey @antfu , I've not seen your messages earlier and I'm really sorry for that.

I'm completely okay with integrating vue-use-sound as an integration for vueuse, as long as I keep the vue-use-sound repository.

Just to mention that it would only be for "comfort" purposes, as vue-use-sound already works completely fine as a standalone Vue 2 or 3 composable.

If @yooneskh could explain why he needs this instead of just installing vue-use-sound as a regular package it would be very interesting to me.

**Comment by Tahul** [comment]
Hey @antfu, now that you created an org for vueuse, I would be glad to add the repository to it if you are interested in vue-use-sound joining the org!

If you wish for the package to join the org but it needs any modification, please let me know and I'll update it accordingly.

Great news that you created an org for vueuse, I'll be glad to contribute to it for my upcoming packages.

👋

**Comment by antfu** [comment]
Hi @Tahul, I was just about to ask you if you are interested in joining the org, well done on the project! So yeah, I am happy to have `vue-use-sound` joined if you'd like to! 

Just sent you the invitation to the org and please free feel to transfer the repo over :) You will have full access to the repo as you would now. About the package name, you can still use `vue-use-sound` or if you'd like, I can invite you to the npm org as well where can you can have `@vueuse/sound`. The only thing I'd suggest is that using the name exported instead of the default, which will have more flexibility for the future extensions and the overall consistency of VueUse, something like

```ts
import { useSound } from 'vue-use-sound'
```

What do you think?

**Comment by Tahul** [comment]
I would be glad to be part of the npm org too and use @vueuse/sound which feels better to me. 😄 

I will be switching the export type too, to stick with your convention.

**Comment by Tahul** [comment]
Everything seem to be done on my part.

https://github.com/vueuse/sound is the new place to go.

I've added a depreciation warning on vue-use-sound on the NPM side.

Also updated the API and export methods on the recommendations of antfu to stick with the vueuse conventions.

**Comment by antfu** [comment]
Awesome, thanks!

**Comment by antfu** [comment]
https://vueuse.js.org/add-ons.html :P
