### ISSUE TITLE
Feature Proposal: Add Barcode Detector Utility

### ISSUE THREAD

**Issue by hslee2008** [vueuse/vueuse#2720]
### Clear and concise description of the problem

I am not sure if this is a good idea, but there are quite a lot of instances Barcode Detection API can be used.

https://developer.mozilla.org/en-US/docs/Web/API/Barcode_Detection_API

Maybe just a handler of file, urls, images and return the raw value using the barcode detection api.

### Suggested solution

This function could be inside the `Browser` category.

`useBarcodeScanner`, `useBarcode`, `useBarcodeDetection`, e.t.c.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Alfred-Skyblue** [comment]
I think this function is unnecessary for the time being. It should be noted that at present, this API requires specific system support, Mac system or mobile phone system, currently Windows system does not support it, and only Chrome browser supports it, other browsers do not support it.

**Comment by HyunseungLee-Travis** [comment]
Well, APIs such as EyeDropper API is only supported in desktop Chrome, Edge, and Opera. It doesn't support mobile entirely.

But, I think Vueuse still has this tool because it is useful in certain cases.

That's why there is the `isSupported` in `useEyeDropper()`.

I think the Barcode Detector API could also be useful in certain cases especially in mobile apps.

**Comment by hslee2008** [comment]
There are some contributions, so it isn't stale.
