### ISSUE TITLE
[bug]: Infinite scroll loadMore hook keeps getting triggered

### ISSUE THREAD

**Issue by baiwusanyu-c** [vueuse/vueuse#3390]
### Describe the bug

`useInfiniteScroll` loadMore hook keeps getting triggered.

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAjAAGSbEyak9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKkleDArGQMPkGWhshQCKRIBRgxGYwEQmms2GbI5XMQJPJlOpG0Q2z2hwAuswjHQDMa0KAAIJgMCTBboUCpLUGCCpIgAHio2RU1iMAF4ADogTx5gB8OfMKjLqfTxAotQ4uZAwVopnMVETECLJbLnZUwGApjjKgOBw7neTwzTxGL2FH48Lz2F0iIdC1dWk3YziBMBxqHFmKgA5As9yWl9qOKve3iAJLYANZVIAiRSgwD7e7vcOm6cuqII-YEszbBkFXTwVCzdcjG0bBSAiex-3kIC3FbUDwO0DBiUYFRGgw9oMIAFgwgBWDCADYfVgv8oJua9bwbB8dwibRh08Rhh20Rws0LbthxUACEKDbB4GkXRkJbaQICjQxyEmfjBOEgBqFRiW4xCxIkgwpLAa5dG0SZdNDDgKhCSYjB3PBtF7GShLQFQCIHDDtAAfQwuh2M4yz5NMexyLLI5h17NMgIgWxEGsskBxLEt7EZQcgA

### System Info

```Shell
System:                                                      
    OS: Windows 10 10.0.19045                                  
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 1.19 GB / 15.74 GB                                 
  Binaries:                                                    
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE           
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD             
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD              
    pnpm: 8.6.12 - ~\AppData\Local\pnpm\pnpm.CMD               
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.76)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/core: ^10.4.1 => 10.4.1
    vue: ^3.3.4 => 3.3.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Alfred-Skyblue** [comment]
`useInfiniteScroll` can only be used on scrollable elements. You should give `el` a fixed height and set it to `overflow-y: auto` or `overflow-y: scroll`. Since your `el` is not scrollable, `scrollHeight === clientHeight`, which will keep triggering `loadMore`. You should use it like this: [Playground](https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAjAAGSbEyak9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKkleDArGQMPkGWhshQCKRIBRgxGYwEQmms2GbI5XMQJPJlOpG0Q2z2hwAuswjHQDMa0KAAIJgMCTBboUCpLUGCCpIgAHgAhBQKC4qKDkKEgypdIg6PA+mgVGTSWBNgBuFSsHJGKIUEJl8QcKUGWsZgB8AB1sMmqNkVNYjABeXsgTyTlS5kJBidmosl6Rl4kAVkrNbrDabLdnEg7k775hUZ8Hw+IFFqHEXwVopnMVETEGP-bPH5UwGApjjKgOBzvh+ybDEOxAniBYHds8wrSEQdBanU0hfiOiAmAcNTtngKgAOQLDh-YIdqHDIT+eIAJLYAGWSpACh4RP+mGzLhDo3JydSIAR2D9jM2C5iongqGOqFGNo2CkBE9g8fI-HPtIrjCaO2gYMSjAqI0antGpAAsanrmpABsPpSdx4k3JR1H3nR7YRNoQGeIwQHaI4Y7dl+QEqLx-FBtg8DSLoQluC+UaGOQkw+X5AUANTlh5QXySFBhhWA1y6NokwZaGHAVCEkxGFh2g-hF-lluu-5qdoAD6al0C5bnFdFpj2CZZ5HEBP5DrmEC2Iga6kv+-b2IyzCSnUQ64KkUbkDGIBxmACZJrwF7EEBtQqoueDyKwk5AaU8CLkEK4UJu-XPhwMBoGdMDHaSpI7aejaeouAB+nlSvdZ6pJs0iLtwKqIBwH0qGAi6NEDpRjQDi7tvwNBUPdJ7nsgkDmF9P2TtpmwGMe34qMQoVpABIHI91iMqMmJOo566MsNhV1oIdfQUAAnLdQXnWg3jQMEIQ3TOeCLtIFBgyA3YALLsJCuMJqUglE3cKMQaB2TQcwba-EQNDUYgAAK7aDIVQEy54ZYAtIki+Y5p740lvUqAAcqQeCyxwVsHENAEHEAA)

**Comment by baiwusanyu-c** [comment]
Can this be improved? Scrollbars may not always exist in the dom🤔

**Comment by Alfred-Skyblue** [comment]
We cannot determine whether the current element can scroll. We can expose the `immediate` parameter to allow users to choose whether to execute it immediately during initialization. This can help avoid the issue of infinite triggering of `onLoadMore` when the current element is not scrollable during initialization. `onLoadMore` will only be triggered when users manually scroll to the bottom.

**Comment by Alfred-Skyblue** [comment]
> We cannot determine whether the current element can scroll. We can expose the `immediate` parameter to allow users to choose whether to execute it immediately during initialization. This can help avoid the issue of infinite triggering of `onLoadMore` when the current element is not scrollable during initialization. `onLoadMore` will only be triggered when users manually scroll to the bottom.

This method is invalid.

**Comment by toniengelhardt** [comment]
I also see this on OS X + Chrome. If I just use the exact example implementation from the package, but stop adding elements when the list length is 100, the callback keeps firing infinitely when I scroll all the way to the bottom. Would be nice if there was a way to set a "complete" flag or simply return false from the callback to remove the listener when the list is complete.

**Comment by toniengelhardt** [comment]
Reproduction with the original example from the docs. Just added a `console.log` and a limit for the list. 

https://stackblitz.com/edit/infinitescroll-infinite-bug

**Comment by AntonioMilicic** [comment]
Any progress regarding this issue?

**Comment by alvaromat** [comment]
@antfu This is still happening when the element passed is a ref and it is unmounted.
