### ISSUE TITLE
[useIDBKeyval] Unable to read file data

### ISSUE THREAD

**Issue by Ocyss** [vueuse/vueuse#3619]
### Describe the bug

The specific problem arises when attempting to set an object containing a file object into IndexedDB. Although the value is successfully set in IndexedDB, upon refreshing the page and attempting to retrieve the value, it returns the default value rather than the previously set value.
```ts
const wordFile = useIDBKeyval<SettledFileInfo | object>(
  'wordFile',
  { foo: 'bar' },
  {
    deep: false,
    shallow: true,
  },
)
```

![QQ截图20231206023044](https://github.com/vueuse/vueuse/assets/68412205/1d7544dc-d96c-4b8e-85af-f8efab7ccc32)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-8ltoev?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Windows 11 10.0.23595
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 15.43 GB / 31.91 GB
  Binaries:
    Node: 20.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.11.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.49), ChromiumDev (121.0.2248.1)
    Internet Explorer: 11.0.23595.1001
  npmPackages:
    @vueuse/core: ^10.7.0 => 10.7.0
    @vueuse/integrations: ^10.7.0 => 10.7.0
    vue: ^3.3.4 => 3.3.10
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Doctor-wu** [comment]
Hello @Ocyss , That's not an issue of `useIDBKeyval`. In fact, in the reproduction, you loged the value when the component is just mounted while the hooks are reading values from indexdDB, so you get a initial value instead of the value stored in the indexdDB. You can use `computed` or `watch` to get the value while data are updated~
<img width="644" alt="CleanShot 2023-12-06 at 11 18 57@2x" src="https://github.com/vueuse/vueuse/assets/44631608/b6e724c5-5c0f-4dd0-a841-ec58fea62d02">
<img width="809" alt="CleanShot 2023-12-06 at 11 19 04@2x" src="https://github.com/vueuse/vueuse/assets/44631608/7a19cfc8-b8c9-424a-8178-0bfb76df1fc6">
