### ISSUE TITLE
useSortable doesnt work with SortableJS groups

### ISSUE THREAD

**Issue by dpi** [vueuse/vueuse#3647]
### Clear and concise description of the problem

I'd like to be able to use `useSortable` with multiple lists, and be able to move items to and from lists with common groups.

### Suggested solution

```js
const list1 = ref([
  { id: 1, name: 'a' },
  { id: 2, name: 'b' },
])
const list2 = ref([
  { id: 3, name: 'c' },
  { id: 4, name: 'd' },
])
const options = {
  animation: 150,
  group: 'foo',
}
useSortable(el1, list1, options)
useSortable(el2, list2, options)
```

When dragging items between rendered list 1 and list 2, `useSortable` should detect new target groups and move values between the two lists.

Currently, `useSortable`, and particularly `moveArrayElement` are not aware of multiple lists or acknowledge group capabilities.

To detect group changes, compare from and to.

Note, you'd need to track a mapping of htmlelement + list as I dont think SortableJS passes along group metadata + modifications on its own.

```js
const fn = evt => {
  const fromElm = evt.from
  const toElm = evt.to
}
const options = {
  ...
  onEnd: fn,
};
```

### Alternative

Perhaps there is some other solution like multidimensional arrays, but I think the above example gets the idea across.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Alfred-Skyblue** [comment]
Currently, `useSortable` only implements drag-and-drop sorting for a single list. Due to the need for maintaining additional documentation and use cases for sorting and cloning between multiple lists, as well as facing various challenges related to grouping, I have developed [`vue-draggable-plus`](https://github.com/Alfred-Skyblue/vue-draggable-plus). You can use it temporarily to achieve this functionality. Of course, you also have the option to use `useSortable` and implement the drag-and-drop sorting functionality between multiple lists on your own.

**Comment by Blacknife** [comment]
These restrictions should be described in the documentation so that people don't waste a lot of time before stumbling upon them
