### ISSUE TITLE
`useMagicKeys()` does not work with native Edge shortcuts

### ISSUE THREAD

**Issue by spaceemotion** [vueuse/vueuse#3685]
### Describe the bug

I am trying to add a shortcut for toggling between light+dark theme, like Notion. However, in Edge `CTRL+SHIFT+L` does a "paste clipboard into URL and do a search" instead.

From what I could tell, the Keyboard Lock API seems to support this, as opposed to the "old" way of using key events:
- https://developer.mozilla.org/en-US/docs/Web/API/Keyboard/lock
- https://stackoverflow.com/a/66070578/1397894

### Reproduction

https://stackblitz.com/edit/vitejs-vite-8mg8fc?file=src%2FApp.vue

The console log some output, but in Edge it just closes the site. Works as expected in Firefox.

### System Info

```Shell
Edge: Version 120.0.2210.91 (Official build) (64-bit)

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 34.26 GB / 41.14 GB
    Container: Yes
    Shell: 3.6.1 - /usr/bin/fish
  Binaries:
    Node: 20.2.0 - /mnt/wslg/runtime-dir/fnm_multishells/6059_1703759868731/bin/node
    Yarn: 1.22.19 - /mnt/wslg/runtime-dir/fnm_multishells/6059_1703759868731/bin/yarn
    npm: 9.6.6 - /mnt/wslg/runtime-dir/fnm_multishells/6059_1703759868731/bin/npm
    pnpm: 8.12.1 - /mnt/wslg/runtime-dir/fnm_multishells/6059_1703759868731/bin/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SimbaOvO** [comment]
Hi, I modified your demo and it works fine for me. It may have solved your problem. Try it: [Demo](https://stackblitz.com/edit/vitejs-vite-gjmzfr?file=src%2FApp.vue)

But here's another tip: If you try to override some shortcuts on the browser, there's a small chance that it'll fail, because it's a limitation of the browser, and it has nothing to do with `vueuse` / `keyboard.lock()`. 

e.g. **Open a new window**:`Ctrl+T (Windows)` / `Command+T (Mac)` will not be overridden. Be careful. :-D

**Comment by spaceemotion** [comment]
@SimbaOvO thanks! that seem to have worked. I think i will still leave this open as the current behavior isn't quite expected - at least to me. Maybe the magic keys can use the keyboard lock stuff in the background so the extra listener is no longer needed down the line?

**Comment by SimbaOvO** [comment]
@spaceemotion Okay, maybe I get you. But I think if you want to implement this feature, it would be better to put in another hook, like `useMagicKeysLock`(?), for a couple of reasons.

1. Functional: `useMagicKeys` seems to have been designed more to listen for shortcuts and extended custom function. But the `lock()` is just a lock.

2. Compatibility: `lock()` is still an experimental feature, and it doesn't seem to be well supported by the likes of Firefox and Safari. [Browser Compatibility-MDN](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard/lock#browser_compatibility)

3. Is that my problem?🤔️ In my demo, `lock()` didn't lock the shortcut and didn't do what you'd expect. [Demo](https://stackblitz.com/edit/vitejs-vite-vqtwwk?file=src%2FApp.vue)

All in all, I personally suggest that maybe it's not a generalized feature yet. Because `useMagicKeys` already provides enough extensibility. More suggestions may be needed and can wait for maintainer's suggestions.
