### ISSUE TITLE
useInfiniteScroll  Scroll up distance does not take effect

### ISSUE THREAD

**Issue by yoruxyy** [vueuse/vueuse#3719]
### Describe the bug

![image](https://github.com/vueuse/vueuse/assets/152286941/16867f4f-b6a5-460c-996f-d4fc84f59973)

When scrolling up, distance does not take effect

### Reproduction

https://vueuse.org/core/useInfiniteScroll/

### System Info

```Shell
windows11，
nuxt 3.9.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by joeldomke** [comment]
Did you find a solution? I am running into the same issue.

I think the problem is, that a top offset is passed in here: https://github.com/vueuse/vueuse/blob/1808c650edda7e703240c140b07741665df41065/packages/core/useInfiniteScroll/index.ts#L58-L64

And then the top arrived state is checked here:
https://github.com/vueuse/vueuse/blob/1808c650edda7e703240c140b07741665df41065/packages/core/useInfiniteScroll/index.ts#L96-L98

But, when using `flex-direction: column-reverse`, `useScroll` uses the bottom offset to compute the top arrived state:
https://github.com/vueuse/vueuse/blob/1808c650edda7e703240c140b07741665df41065/packages/core/useScroll/index.ts#L255-L262

With `bottom` being calculated as:
https://github.com/vueuse/vueuse/blob/1808c650edda7e703240c140b07741665df41065/packages/core/useScroll/index.ts#L246-L249

This means the distance is never taken into account.
