### ISSUE TITLE
[Bug report] computedWithControl is triggering "Computed is still dirty after getter evaluation" warning

### ISSUE THREAD

**Issue by meteorlxy** [vueuse/vueuse#3794]
### Describe the bug

Related issue: https://github.com/vuejs/core/issues/10341

`computedWithControl` will trigger the warning in vue 3.4.19:

```text
[Vue warn] Computed is still dirty after getter evaluation, likely because a computed is mutating its own dependency in its getter. State mutations in computed getters should be avoided.  Check the docs for more details: https://vuejs.org/guide/essentials/computed.html#getters-should-be-side-effect-free
```

<img width="478" alt="image" src="https://github.com/vueuse/vueuse/assets/18205362/133151a9-8fa9-4cf9-bab4-954c7caa3f1a">
<img width="544" alt="image" src="https://github.com/vueuse/vueuse/assets/18205362/a81ffcf6-30f9-4193-9462-0597e978fe49">

### Reproduction

https://stackblitz.com/edit/vitejs-vite-bvw5gp?file=src%2FApp.vue

### System Info

```Shell
N/A
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by meteorlxy** [comment]
cc @Doctor-wu

**Comment by Doctor-wu** [comment]
@meteorlxy Hey, `computedWithControl` is not a `computed` under the hood, it just combine the usage of `watch` and `computed`. `computedWithControl` has side-effect since it need to maintain some refs internally. So it's not suggested to use `computedWithControl` in a real `computed`, you can use `watch` which is designed for side-effect operation, or use `syncRef` for ease.

**Comment by Doctor-wu** [comment]
Here is an example
<img width="1264" alt="CleanShot 2024-02-19 at 00 23 05@2x" src="https://github.com/vueuse/vueuse/assets/44631608/6d96e2ce-dcaf-4acd-9e4b-21010998d2e8">

**Comment by Doctor-wu** [comment]
Submitted a PR for `vuepress` case
https://github.com/vuepress/core/pull/1501

**Comment by meteorlxy** [comment]
@Doctor-wu I see. Thanks for looking into that.

It looks like a workaround in userland code. Is it possible to fix in vueuse side? If not, we'd better put a warning in the docs.

**Comment by Doctor-wu** [comment]
> @Doctor-wu I see. Thanks for looking into that.
> 
> It looks like a workaround in userland code. Is it possible to fix in vueuse side? If not, we'd better put a warning in the docs.

A warning is a good point

**Comment by Mister-Hope** [comment]
I suggest not closing this issue too casually. it's weird to say:

> `computedWithControl` is not a `computed` under the hood.

Then why a name with `computedWithControl`? There are people reporting the same problem with VueUse functions, so it can prove that even VueUse contributors can make misuse them and these PRs can be approved and added to repo.

I would suggest one of the 2 things:

- try to make `computedWithControl` work with Vue 3.4 new reactivity system
- deprecate `computedWithControl` and any other api with `/** @deprecated */` which may confuse the users, and give them new name.

**Comment by Doctor-wu** [comment]
@Mister-Hope 
> Then why a name with computedWithControl?

It just combines the usage of `watch` and `computed`, to help users understand how to use this function. It uses `customRef` to implement a controllable "computed" usage-like ref.

This function was added to `vueuse` almost 2 years ago, and at that time, `vue` didn't have a `new reactivity system` yet, so it's hard to say it's contributors misuse.

>try to make computedWithControl work with Vue 3.4 new reactivity system

`computedWithControl` works well in the new reactivity system, it's reasonable to have side-effects to implement a function like this. The warning  was caused by user's misuse in computed, so it make no sense to mark this function as deprecated as well.

**Comment by Mister-Hope** [comment]
Again:

1. computed can be used in another computed
2. computedWithControl sounds like a computed
3. Even if users do not manually use computedWithControl (in that case a docs warning would be fine), they can still get it from VueUse functions
4. Using computedWithControl inside computed is wrong.

People will probably misuse it under 1, 2, 3, so it leads to 4

That's the problem I am talking, again, unless VueUse only use this one internally, otherwise I don't think I am convinced by any of the reasons above.

**Comment by Doctor-wu** [comment]
I think mark this function is not a computed will be helpful, thanks for your suggestions!

**Comment by Mister-Hope** [comment]
Yes, that's something I want to express, I do think that VueUse should do something to avoid people misuse them, for example, the `useActiveElement` (here: https://vueuse.org/core/useactiveelement/#useactiveelement) use watch in examples, but you can not expect developers to "understand" that we can only watch this and should never generated other state using computed with it.

It should be a historical problems, so hope you can open another issue to track it and help the community, while I am facing the problem in VuePress developing, I also notice a lot of similar noise upstream in Vue core about it after vue@3.4.19 raise a warning about it. Some of the issues are misuse of computed by users, while some of them are related to VueUse. I hope the second one can be nicely warned here.

**Comment by Mister-Hope** [comment]
At least in my side, I believe returning a `computedWithControl` could be a bad thing for users, just take the `useActiveElement` as example, we can definitely return a standard computed so that users can generate other state with computed.😉 Can this be considered, and do you think a full check in all apis is helpful?

**Comment by Doctor-wu** [comment]
That's a hard one to check the full apis, it's more feasible to rely on the power of community, PR are welcome for solve some historical problems like this.

>while some of them are related to VueUse

For this part, if you find `vueuse` misused new reactivity instead of misused by userland's code, it's greatly encouraged to submit issues.

What ever, I will check `useActiveElement` case later.

**Comment by p1xel007** [comment]
I'm getting this warning while using "useStorage" form VueUse @Doctor-wu

**Comment by Doctor-wu** [comment]
> I'm getting this warning while using "useStorage" form VueUse @Doctor-wu

Did you use `useStorage` in computed, or it just throw this warning by itself?

**Comment by p1xel007** [comment]
> > I'm getting this warning while using "useStorage" form VueUse @Doctor-wu
> 
> Did you use `useStorage` in computed, or it just throw this warning by itself?

I'm using it in Pinia store

**Comment by Doctor-wu** [comment]
> > > I'm getting this warning while using "useStorage" form VueUse @Doctor-wu
> > 
> > 
> > Did you use `useStorage` in computed, or it just throw this warning by itself?
> 
> I'm using it in Pinia store inside getter

Can you show me your code about this?

**Comment by p1xel007** [comment]
> > > > I'm getting this warning while using "useStorage" form VueUse @Doctor-wu
> > > 
> > > 
> > > Did you use `useStorage` in computed, or it just throw this warning by itself?
> > 
> > 
> > I'm using it in Pinia store inside getter
> 
> Can you show me your code about this? As a side note, Pinia's `useStore` has side effect itself, look at this for more information [vuejs/core#10341](https://github.com/vuejs/core/issues/10341)

Pinia store:
`import { defineStore } from 'pinia';
import { useStorage } from '@vueuse/core';

export const UserStore = defineStore({
    id: 'user',

    state: () => ({
        user_data: {}
    }),

    getters: {
        isLoggedIn: () => useStorage('isLoggedIn')
    },

    actions: {}
});

export default UserStore;
`


This is how I called it: (And this is where the warning shows from)
`const userLoggedIn = UserStore().isLoggedIn;`

**Comment by Doctor-wu** [comment]
Is there any warning if you just returned a static value like
```typescript
  getters: {
    isLoggedIn: () => true,
  }
```

**Comment by p1xel007** [comment]
> Is there any warning if you just returned a static value like
> 
> ```ts
>   getters: {
>     isLoggedIn: () => true,
>   }
> ```

No, the warning disappear when I return anything other than VueUse function

like as a warkaround I'm using `localStorage.getItem('isLoggedIn')` instead

**Comment by Doctor-wu** [comment]
![CleanShot 2024-02-21 at 10 24 33@2x](https://github.com/vueuse/vueuse/assets/44631608/21788a86-4dfe-4646-b1ee-a88a38f93b12)
In fact, getters in Pinia is a computed as well, so it will cause that warning.

**Comment by p1xel007** [comment]
> ![CleanShot 2024-02-21 at 10 24 33@2x](https://private-user-images.githubusercontent.com/44631608/306473563-21788a86-4dfe-4646-b1ee-a88a38f93b12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODI3NDAsIm5iZiI6MTcwODQ4MjQ0MCwicGF0aCI6Ii80NDYzMTYwOC8zMDY0NzM1NjMtMjE3ODhhODYtNGRmZS00NjQ2LWIxZWUtYTg4YTM4ZjkzYjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAyMjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNzJjNWIxNDg4ZDExNzViZTZmNTVhYzhkN2U5ZjI1YTYwMDQ3NGIyMzdkNWQ0NGM3ZDhhNDE3MGMyNjJhOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jbJBBA2kSfZoVOX2uJMeoER_ehcvXXbkdF8XHfnvnIQ) In fact, getters in Pinia is a computed as well, so it will cause that warning.

I see, what's the approach to resolve this warning?

**Comment by Doctor-wu** [comment]
You can extract the `useStorage` outside the getters like on the top of the file, and use the return value in the getters.
```typescript
  const isLoggedInRef = useStorage('isLoggedIn')
  ...
  getters: {
    isLoggedIn: () => isLoggedInRef.value
  }
```

**Comment by Doctor-wu** [comment]
BTW, it's not suggested to directly reply under a closed issue, you can create a new one next time.
