### ISSUE TITLE
onStartTyping demo bug

### ISSUE THREAD

**Issue by rixleft** [vueuse/vueuse#3825]
### Describe the bug

When I read the article on the official website, I noticed that there was no difference in the performance of the two input boxes in the demo project. I downloaded version 10.8.0 of the project with the editor and found that the editor prompts me that this judgment is always  True. Do you think there is a problem here?
![bug](https://github.com/vueuse/vueuse/assets/105371446/aafc32c0-ae4b-4971-bd22-81cbcd825423)

### Reproduction

https://www.vueusejs.com/core/onStartTyping/#onstarttyping

### System Info

```Shell
window11 chrome
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by noook** [comment]
First of all, according to the documentation:
> "Fires when users start typing on non-editable elements."

That means it will be triggered only if the user starts typing in something that is:
- not an input
- not a textarea
- not an element with the `contenteditable`

That implies that the callback should not be called when typing in any input. So the condition you are checking for indeed always returns `true`.

However, the editor cannot be aware of such information, this was just my observation. Regarding the editor error, I think the editor believes that the two types in your if block never overlap and thus will always return `true`. However I checked on a Typescript playground and `HTMLInputElement` should extend `Element` so this should still be possible, I'm as confused as your editor here.

Last point, please share either a text version of the warning you have in your editor, or even better an english translation so that every user can understand the issue

**Comment by OrbisK** [comment]
As @noook said, this is not an implementation issue. So I will close this issue for now.
