### ISSUE TITLE
useFullScreen isn't working on the iphone 13 chrome browser

### ISSUE THREAD

**Issue by shba007** [vueuse/vueuse#4108]
### Describe the bug

useFullScreen isn't working on the iphone 13 chrome browser

### Reproduction

https://stackblitz.com/edit/nuxt-starter-a2xb7r?file=app.vue

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vueuse/nuxt: ^10.11.0 => 10.11.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Batyodie** [comment]
It looks like the problem is related to the [fullscreen api](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) support in iOS. If I understand correctly, chrome in ios is just a wrapper for the safari webkit browser, and if the fullscreen api does not work in safari ios, it will not work in chrome.

It looks like there is nothing that can be done about this, just wait for apple to fix this [problem](https://forums.developer.apple.com/forums/thread/133248)

Here is the current [API support](https://caniuse.com/?search=fullscreen%20api).
