### ISSUE TITLE
BUG | `functionName` | Type for `UrlParams` is incorrect

### ISSUE THREAD

**Issue by Zelzahn** [vueuse/vueuse#4388]
### Describe the bug

According to the type (`export type UrlParams = Record<string, string[] | string>`) a parameter is either a `string` or a `string[]`, but if the parameter does not exist it is `undefined`.

### Reproduction

https://vueuse.org/core/useUrlSearchParams/?foo=bar&vueuse=awesome#type-declarations

### System Info

```Shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 16.24 GB / 31.02 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.local/share/mise/installs/node/22.11.0/bin/node
    npm: 10.9.0 - ~/.local/share/mise/installs/node/22.11.0/bin/npm
    pnpm: 9.11.0 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chromium: 131.0.6778.85
  npmPackages:
    @vueuse/core: ^12.0.0 => 12.0.0 
    vue: ^3.4.18 => 3.5.13
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by huang-julien** [comment]
Hi :wave: 

i'm not sure what's the issue here. Are you talking about the default type returned by `useUrlSearchParams` or about the documentation ? 

`UrlParams` is the default type for `useUrlSearchParams`, you can change it by typing the type parameter of `useUrlSearchParams` to enforce stricter types. 
And the definition is still correct because `useUrlSearchParams` does return a `Record<string, string|string[]>`. The definition of `Record` is that it's an object with a pair of key/values.
