### ISSUE TITLE
Maybe bug in createGlobalState with using vue-router

### ISSUE THREAD

**Issue by brokolosov** [vueuse/vueuse#466]
store.ts
```es6
import {createGlobalState, useStorage} from '@vueuse/core'

export const useState = createGlobalState(() => {
    return useStorage('user', {
        user: null
    })
})
```

main.ts
```es6
createApp(App)
    .use(router)
    .mount('#app')
```

app.vue
```es6
import {useRouter} from 'vue-router'
import {useState} from '~/store'

const state = useState()
const router = useRouter()

console.log(router)
console.log(state.value)
```

The browser throws the warn "[Vue warn]: inject() can only be used inside setup() or functional components. at <App>" and router undefined in console.

But if in main.ts added line ```.provide('state', useState())``` then warn gone...

**Comment by antfu** [comment]
I didn't get it, can you share a minimal repro? Thanks

**Comment by brokolosov** [comment]
here you are [link](https://github.com/brokolosov/vueuse)

**Comment by wheatjs** [comment]
As a workaround you can declare `const router = useRouter()` before `const state = useState()`.

I'm thinking the issue comes from `withScope` here https://github.com/vueuse/vueuse/blob/main/packages/core/createGlobalState/index.ts#L4

Perhaps it has something to do with `createApp` portion, not sure tbh though.

**Comment by brokolosov** [comment]
heh.... that helped, thanks

**Comment by antfu** [comment]
To use router globally, I would recommend to do:

```ts
// router.ts

export const router = createRouter()
```

```ts
// main.ts

import { router } from './router'

createApp().use(router).mount()
```

```ts
// whatever

import { router } from '../router'

const route = router.currentRoute
```

`createGlobalState` is only provide as a workaround for now. To have full support of it, we will need https://github.com/vuejs/rfcs/pull/212, which likely be Vue 3.2

**Comment by drmercer** [comment]
I also ran into this issue, and the cause - i.e. the `useState()` call happening before the `useRouter()` call, because the former mutates global state inside Vue - was not obvious. I fixed it by replacing `createGlobalState` with my own implementation that uses the [new `effectScope` API](https://v3.vuejs.org/api/effect-scope.html) (linked above back when it was still an RFC). Any chance we can make that change in VueUse itself so others don't run into this hard-to-debug issue?
