### ISSUE TITLE
useAxios: request should be canceled in onUnmounted

### ISSUE THREAD

**Issue by gkubisa** [vueuse/vueuse#521]
If a request is not resolved yet and the component in which `useAxios` was called is unmounted, the request should be aborted. I really see no reason for allowing the request to complete in that case.

**Comment by wheatjs** [comment]
Hmm I'm not sure if that is a good idea, especially if it is something like post data this may introduce unexpected behavior for user. Maybe we can add something to the docs about it showing people how to do it

**Comment by cawa-93** [comment]
It seems this can be easily implemented at the component level:
```js
const { abort } = useAxios( ... )
tryOnUnmounted(abort)
```

**Comment by wheatjs** [comment]
I agree, it is pretty simple to do at the component level so we should leave it there. One problem I see with aborting it automatically on the component being unmounted is if someone used a response hook to create some toast notification or something it might not work if the component is unmounted before the request is complete. So this should probably be left up to the user as a more intentional behavior.
