### ISSUE TITLE
[useFetch] How to get the result data?

### ISSUE THREAD

**Issue by xieyezi** [vueuse/vueuse#537]
I request server data in `setup()` function, this is my request:

```ts
setup() {
   ...
    const url = ref('http://xieyezi.com:9003/mock/11/airi/index')
    const { data,isFinished } =  useFetch(url).get().json()
    console.log('data:', data) 
    console.log('data.value:', unref(data))
    ...
}
```
when finish request ,  which `data` console is :

![image](https://user-images.githubusercontent.com/16821989/119599822-53d6a300-be18-11eb-910f-0865873b805e.png)

But the `unref(data)` is null, So how can I get the `data.value` ?

**Comment by wheatjs** [comment]
When you console log `data` it is a reference and will also update in the console when the value changes. Logging `data.value` will give you the value of `data` at the exact time you log it. Instead you can do something like. You could either use a `watch` to wait for the data like

```ts
const { data, isFinished } = useFetch()

watch(isFinished, () => {
  if (isFinished)
    console.log(data.value)
}):
```

or you can use [until](https://vueuse.org/shared/until/)
```ts
const { data, isFinished } = useFetch()

await unil(isFinished).toBe(true)
console.log(data.value)
```

**Comment by xieyezi** [comment]
@wheatjs I got this , thank you!

**Comment by kissu** [comment]
@wheatjs sorry for the question, but how do you access a nested field from `data` in Vue3 (still new to CAPI)?
I'm using it as following
```js
const { data } = useFetch('https://jsonplaceholder.typicode.com/users/1').get().json()
console.log('data', data)
```
In my network

![image](https://user-images.githubusercontent.com/5133074/145925037-a4d98e13-d0a9-4310-b211-933f7754e5c9.png)
---
In my console

![image](https://user-images.githubusercontent.com/5133074/145925120-dfeaab0e-8a10-48a0-81ff-047e35545cc1.png)

Tried a lot of unwrapping, syntax etc...but I cannot reach `email` in any script tag (with `setup` or even without).

Works fine in the template so I guess it's some kind of [nested `.value` thing](https://stackoverflow.com/a/67579212/8816585) that needs to be done if I want to assign it to a `data()` variable?

**Comment by wheatjs** [comment]
@kissu `useFetch` is async, so you will not be able to access it immediately even if it shows up in the console when you log it. So to access it you will need to `await` using something like `await unil(isFinished).toBe(true)` or watch the data object itself. So to access the email field you can try one of these

https://stackblitz.com/edit/vitejs-vite-avluye?file=src/App.vue
```html
<script setup>
const { data } = useFetch('https://jsonplaceholder.typicode.com/users/1').get().json()

watch(data, (user) => {
  console.log(user.email) // or data.value.email
})
</script>
```
or

https://stackblitz.com/edit/vitejs-vite-golgaa?file=src%2FApp.vue
```html
<script setup>
const { data, isFinished } = useFetch('https://jsonplaceholder.typicode.com/users/1').get().json()

await unil(isFinished).toBe(true)

console.log(data.value.email)
</script>
```

Using console.log can be kind of misleading in this way because it will only actually resolve the object when you expand the tree. So the data may not actually be there when you log it, but when you go to expand the tree from a console.log it will be there as it just resolved the data.

**Comment by kissu** [comment]
Damn, works perfectly fine now! Thanks for the quick reply. ❤️ (you got a typo `unil` but I guessed it)

Yeah, I was kinda surprised that I didn't needed an `await useFetch` at first but I wasn't sure if `console.log` was the culprit or the fact that it's a `ref`. I've tried to `await` further down too with various syntax but nothing worked.
I totally see how this is working now but I would never been able to guess this without seeing the [watch](https://vueuse.org/functions.html#watch) section and googling didn't helped because it was specific to Vueuse.

This is pretty unfamiliar when compared to a more traditional `async/await` tho (the fact that you need to wrap it with `until` + `toBe(true)`)... 😅 
Is this a decision of the API itself or the way `script setup` works nowadays?
Because this may need to passed down to my team. 👍🏼

**Comment by wheatjs** [comment]
@kissu It was mostly designed with reactive data in mind, but I agree that the `until.toBe` is a bit much. So I created a PR to support this here https://github.com/vueuse/vueuse/pull/1056, should be released in the next version

**Comment by kissu** [comment]
Thanks for being so quick! 🙏🏼

**Comment by ririen** [comment]
Is await working properly? I try to use it in the latest version of the library with useFetch but still doesn't work.

**Comment by kissu** [comment]
Same, this kind of code is just blocking the whole rendering
```js
<script setup>
let users = ref([])
const { data } = useFetch('https://jsonplaceholder.typicode.com/users').get().json()
users = data
</script>
```

Not sure if [useAsyncState](https://vueuse.org/core/useasyncstate/#useasyncstate) can be of any help here.

**Comment by wheatjs** [comment]
Are you guys making sure you are using Suspense when you await your requests?

@kissu This is how you would use the awaitable useFetch like you are trying https://stackblitz.com/edit/vitejs-vite-8mpvbv?file=src%2Fcomponents%2FHelloWorld.vue

**Comment by kissu** [comment]
Alright, I was wondering also why we never used Suspense until I realized that you dumped this into `App.vue` (which looks totally legit to have it at the apex btw).
```html
<template>
  <img alt="Vue logo" src="./assets/logo.png" />
  <Suspense>
    <template #default>
      <HelloWorld msg="Hello Vue 3 + Vite" />
    </template>
    <template #fallback>
      <div style="background: red">LOADING</div>
    </template>
  </Suspense>
</template>
```

Indeed, it works far better with this... Where is the rock for me to hide under and just get forgotten? 😂 
I promise to take the time to learn Vue properly in 2022. In a rush right now. 😓

**Comment by wheatjs** [comment]
Haha don't disappear, I'm more than happy to help when people run into problems 😄
