### ISSUE TITLE
[bug] useStorage default value `null` get's written to localstorage and read as `"null"`

### ISSUE THREAD

**Issue by adrianjost** [vueuse/vueuse#597]
If you set `null` as the default value of `useStorage`, this value get's written to the localStorage on initial execution and is then read as the string `"null"`. This behaviour was most likely introduced with #528 and I suspect it isn't intended. 
All versions >=4.11.1 are affected.

Example:
```
import { useStorage } from "@vueuse/core";
const test = useStorage("key", null);
console.log("Key:", typeof test.value, test.value);

// First load (expected behaviour)
// > Key: object null
// Subsequent loads (broken)
// > Key: string "null"
```

**Comment by antfu** [comment]
Duplicated #452

**Comment by adrianjost** [comment]
I don't think this is a duplicate of #452. My issue is related to reading the value when having `null` set as the default value. This has nothing to do with invalid types or any other typescript warning. It is a behavioural change that isn't documented anywhere.

**Comment by antfu** [comment]
Sorry misread

**Comment by adamdehaven** [comment]
@jeffrey-dot-li I believe this is still an issue in `5.1.4`.

Here's an example:

```js
import { useLocalStorage } from '@vueuse/core'

// bind a string
const name = useLocalStorage('name', null)
```

Just by calling the above, and doing nothing else, if I look at the localStorage in the console, I see the following:

![image](https://user-images.githubusercontent.com/2229946/126363269-c176433d-5702-42d8-88b6-78a20196d4e3.png)

My understanding of the usage is that if the value is set to `null`, no localStorage key/value pair would be stored. Is this not correct?

I can later do `name.value = null`; however, this too does not delete the item from localStorage as it does in the docs example, and instead, again just sets the value in localStorage to a string of `null`

**Comment by antfu** [comment]
@adamdehaven https://vueuse.org/core/usestorage

![image](https://user-images.githubusercontent.com/11247099/126432465-58eeb0e5-e5bf-4dfc-9144-e491fd7a40e8.png)

**Comment by adamdehaven** [comment]
@antfu I'm aware of using the `StorageSerializers`; however, if I update my example to what is shown below, the same behavior is present.

```js
import { useLocalStorage, StorageSerializers } from '@vueuse/core'

const name = useLocalStorage('name', null, { serializer: StorageSerializers.string })
name.value = null
```

Using the code above, setting a data type of `string` to a value of `null` still produces a `string` of `"null"` in localStorage. Explicitly setting a default value of `null` (which is not a string) currently produces an unexpected (and seemingly incorrect) result of a string value of `null`. Am I missing something? 

Shouldn't the default behavior of the `StorageSerializers.string` type remove the value from localStorage if the value set to `null`? 

Really appreciate the help, I'm just trying to understand the behavior and if this is actually the way it **_should_** be working.

**Comment by jeffrey-dot-li** [comment]
Wait ok I think I didn't completely fix the issue in my pull request - I didn't realize that there was `useStorage` and `useLocalStorage` I think I only fixed for `useStorage` not the other one. Just to clarify @antfu whats supposed to be the difference between the two? I'll pull request a fix for `useLocalStorage` as well thanks for bringing this up

**Comment by adamdehaven** [comment]
Just in case this needs to be added: 

I would think the behavior, regardless of whether the type is `string`, `object`, `number`, etc. should be that if a value of `null` is passed (as the default, or the actual value) the item should be removed from storage, regardless of whether it's `localStorage`, `sessionStorage`, etc.

**Comment by adamdehaven** [comment]
@jeffrey-dot-li one question: on your PR, it looks like the serializer is doing this:

```
any: {
    read: (v: any) => (v != null && v !== 'null') ? v : null,
    write: (v: any) => String(v),
  },
```

However, if the value passed is null, why would you want `String(v)` as this will convert it to a string of `"null"` instead of an actual `null` value

**Comment by adrianjost** [comment]
> I think I only fixed for useStorage not the other one.

@adamdehaven I don't think that's the case. `useLocalStorage` is already implemented as an wrapper around `useStorage` so there is no special logic for it.

https://github.com/vueuse/vueuse/blob/9a1b205d1732f9214bb9ba61c2916e75955a5dd1/packages/core/useLocalStorage/index.ts#L19-L22

**Comment by adamdehaven** [comment]
@adrianjost the functionality may be shared, but I believe the [comment I left here](https://github.com/vueuse/vueuse/issues/597#issuecomment-885011139) is what is relevant.

```
any: {
    read: (v: any) => (v != null && v !== 'null') ? v : null,
    write: (v: any) => String(v), // HERE
  },
```

1. Based on this code, if the value of `v` = `null`, when it stores the value, it's converting to a string like `String(null) = "null"`
2. In addition, the [`watchWithFilter` function](https://github.com/jeffrey-dot-li/vueuse/blob/9a1b205d1732f9214bb9ba61c2916e75955a5dd1/packages/core/useStorage/index.ts#L132-L154) is not checking for a string value of `"null"` meaning that the item is not removed. 

The second issue above can be remedied by changing the `if` statement for removing items to the following:

```
if (data.value == null || data.value == 'null')
```

**Comment by jeffrey-dot-li** [comment]
@adamdehaven Oh ok yeah I found the issue its the fact that `watchWithFilter` doesn't trigger when you set the value of a ref to the same as its current value. So in your example `name.value` is already set to `null`, so `name.value = null` doesn't actually trigger the watch hook to delete it from storage

**Comment by adamdehaven** [comment]
@jeffrey-dot-li but I still think the `write` shouldn't be converting the value to a string if `v === null || v === 'null'`

In addition to in the watcher, adding `if (data.value == null || data.value == 'null')` to be safe

**Comment by jeffrey-dot-li** [comment]
In this case, if people are using `null` as the default value of `useStorage`, I personally think that maybe we should have a different method of deleting items from local storage than setting their value to `null`.

The three other solutions I can think of are currently: 
1. Trigger the `watch` hook even if the previous and current value are both null by messing with [`@vue/reactivity`](https://github.com/vuejs/vue-next/blob/f0ca233d8bb101b901f535343707d1177698ddb0/packages/reactivity/src/ref.ts#L118-L122) , which would cause a bunch of undefined behaviour. 
2. Use a different value/symbol for `default` and `delete` operations, for example use `undefined` as the default storage value and `name.value = null` would then trigger the watch hook and still delete it from storage.
3. Have the `useStorage` function return both the storage ref as well as a delete hook, for example: 
```javascript 
const [ state, erase ] = useStorage('name', null, { ... })
state.value = null // Sets the value of the reference in local storage to `null`.
erase() // Deletes the key from local storage.
```

Personally, I think the last option is preferable because it the most transparent and requires the least amount of questionable string inferencing. I'll write a PR implementing it, but its possible I'm wrong about the correct solution here so if I am let me know.

**Comment by adamdehaven** [comment]
Wouldn't simply checking for `null` or `"null"` in the [`watchWithFilter` function](https://github.com/jeffrey-dot-li/vueuse/blob/9a1b205d1732f9214bb9ba61c2916e75955a5dd1/packages/core/useStorage/index.ts#L132-L154) take care of the entire problem?

If the item is always removed if the value is `null` or `"null"` then the issue as described would be resolved, right?

The core issue here is that a string value of `"null"` should never be stored into localStorage unless it is explicitly passed as a string. Since the `write` serializer is converting **everything** to a string with `String(v)` even if a user passes a valid `null` value, that's what is causing the issue.

`String(null)` is always going to return `"null"`

So why not just either check for the value, or change the `write` serializer to something like this where this behavior is prevented:

```
write: (v: any) => (v != null && v !== 'null') ? String(v) : null,
```

**Comment by jeffrey-dot-li** [comment]
Not quite, in my testing the issue is that the watchWithFilter function doesn't even trigger if the previous value is already null and you are trying to set the value to null to delete it

**Comment by jeffrey-dot-li** [comment]
Oh sorry I misread what you meant, yeah maybe null shouldn't be stored even when passed as a default value

**Comment by jeffrey-dot-li** [comment]
> 
> 
> Wouldn't simply checking for `null` or `"null"` in the [`watchWithFilter` function](https://github.com/jeffrey-dot-li/vueuse/blob/9a1b205d1732f9214bb9ba61c2916e75955a5dd1/packages/core/useStorage/index.ts#L132-L154) take care of the entire problem?
> 
> If the item is always removed if the value is `null` or `"null"` then the issue as described would be resolved, right?
> 
> The core issue here is that a string value of `"null"` should never be stored into localStorage unless it is explicitly passed as a string. Since the `write` serializer is converting **everything** to a string with `String(v)` even if a user passes a valid `null` value, that's what is causing the issue.
> 
> `String(null)` is always going to return `"null"`
> 
> So why not just either check for the value, or change the `write` serializer to something like this where this behavior is prevented:
> 
> ```
> write: (v: any) => (v != null && String(v) !== 'null') ? String(v) : null,
> ```

However you can't *not* convert `null` into a string because (unless I'm wrong) everything stored in localStorage must be serialized as a string. If you try to do `localStorage.setItem('name', null)`, you'll get a typeerror because you are passing an object and not a string, and it will be serialized to 'null' in localStorage anyways

**Comment by adamdehaven** [comment]
Right -- I don't want to store `null` (and you are correct, localStorage is key (string) / value (string)

So again, if a user passes `null` it should NEVER be converted to a string and stored as `"null"`

**Comment by jeffrey-dot-li** [comment]
> 
> 
> Right -- I don't want to store `null` (and you are correct, localStorage is key (string) / value (string)
> 
> So again, if a user passes `null` it should NEVER be converted to a string and stored as `"null"`
> 
> So something definitely needs to be changed/updated.

Haha sorry fixed it properly this time my bad, new pr should behave as expected

**Comment by adamdehaven** [comment]
@jeffrey-dot-li I think your changes in the PR may be incorrect. I left a comment

**Comment by adamdehaven** [comment]
@jeffrey-dot-li [left a comment](https://github.com/vueuse/vueuse/pull/642/files#r675080226)
