### ISSUE TITLE
lock axis for usePointerSwipe

### ISSUE THREAD

**Issue by appinteractive** [vueuse/vueuse#616]
Currently the `usePointerSwipe` hook is unusable when you are on mobile due to the fact that it does listen to horizontal AND vertical swipes and cant be configured otherwise. That results in broken scrolling on mobile when I only want to swipe horizontaly on a target. You even can observe that on the documentation page when you try to scroll the page by touch: https://vueuse.org/core/usePointerSwipe/

Why not adding a `axis` prop which acceepts a list of directions? 

Meanwhile is there a workaround? 

The stop method does not help as scrolling is disabled on the swipe element. :(

**Comment by JMaylor** [comment]
I was looking at this and the behaviour with this is a little weird in general...

**My user experience** with the demo page (both on mobile and on desktop emulating mobile):
1. When you first load the page, the swipe doesn't work the first time you try it.
2. After this it does work, then seems to alternate between working and not working with every swipe.
3. Same thing happens with scrolling down the page - if you start the scroll on the swipe button, it alternates between scrolling down the page, or being locked on the swipe button.

I recorded the below to try and demonstrate this:
https://user-images.githubusercontent.com/60825814/131919277-7afb137f-e2af-492b-9060-7325068a94ee.mp4

**What is happening?**
Basically in the `'pointerup'` event listener, the `touch-action` is set to initial:
```ts
useEventListener(target, 'pointerup', (e: PointerEvent) => {
  if (isSwiping.value)
    onSwipeEnd?.(e, direction.value)
 
  isPointerDown.value = false
  isSwiping.value = false
  targetRef.value?.setAttribute('style', 'touch-action: initial') // here
}),
```
Seems like whenever the `touch-action` is set to initial and I try and swipe - the default `pointermove` event listener only fires a few times and then it just stops, and there's no `pointerup` event at all. In the first `pointerdown` event though, the `touch-action` is set to none, which means that the next time you try and swipe, this error doesn't occur since we're starting with `touch-action: none`, rather than `touch-action: initial`.

You can actually physically see that the `pointermove` event only happens a few times - if you load the page on desktop with device emulation, click on the left of the swipe button, and then swipe **_really_** fast - you will actually break the threshold and the swipe button will move, before the event listeners stop - then you're left with the button in this partly-swiped state (see below screenshot) until you interact with it again - since the `pointerup` cleanup didn't ever happen.
![Screenshot 2021-09-02 231935](https://user-images.githubusercontent.com/60825814/131923622-4c30a960-79d8-4461-a858-2fc6704cd67e.png)

Hope this makes some sense - won't claim to have any real knowledge on pointer events but maybe this helps someone else improve it.
