### ISSUE TITLE
Need "restore" to the original version with useRefHistory 

### ISSUE THREAD

**Issue by mockingjet** [vueuse/vueuse#726]
Though "reset" is used to setting data as the latest version. A "restore" function for setting data as the original (first) version is expected too.

**Comment by patak-js** [comment]
We already provide the pieces to create this helper in userland:
```js
const r = ref(0)
const { undo, history, clear } = useRefHistory(r)

const restore = () => {
  r.value = history.value.at(-1).snapshot
  clear()
}
```
But it is complex enough to get right that it would be interesting to get something to make this pattern more straightforward. There is a problem with the word `original` or `initial` because every time you call `clear()` the history is cleaned leaving the current state. I think your idea of `first` is on point here, and we already have a `last` ref. If we expose `first`, we could have:
```js
const r = ref(0)
const { undo, first, clear } = useRefHistory(r)

const restore = () => {
  r.value = first.value.snapshot
  clear()
}
```
I don't know how useful it is though, I think in most apps, you would have a function to create an initial state for your app. So if you are implementing this, it would look more like
```js
const r = ref(0)
const { undo, clear } = useRefHistory(r)

const restore = () => {
  r.value = createInitialState()
  clear()
}
```
The problem with using `first` is that you may clear the history after loading from local storage for example.

Another issue is to decide if this should call `clear()` or not. In an app, we decided to avoid clearing the history because it was still useful to be able to go back. So our restore is directly
```js
const restore = () => {
  r.value = createInitialState()
}
```

Maybe `restore()` is still useful enough, and a boolean could be added to control where to clear the history.

@mockingjet would you like to work on a PR to add `first` to start with? I think that would already allow users to implement this as they see fit. What do you think about `restore` @antfu?
