### ISSUE TITLE
TS2305: Module '"vue-demi"' has no exported member 'ComponentPublicInstance'.

### ISSUE THREAD

**Issue by Shinigami92** [vueuse/vueuse#772]
```node
$ yarn build                
node_modules/@vueuse/core/index.d.ts:5:42 - error TS2305: Module '"vue-demi"' has no exported member 'ComponentPublicInstance'.

5 import { Ref, InjectionKey, ComputedRef, ComponentPublicInstance, UnwrapRef, ToRefs } from 'vue-demi';
                                           ~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by dragomirweb** [comment]
I can confirm, same goes for me, upgraded from 5.1.3 to 6.4.1 using LTS typescript lib. composition api using v1.1.5

**Comment by fk1blow** [comment]
I'm trying to upgrade from 5.1.3 to 6.4.1 and encountering the same issue: `Module '"vue-demi"' has no exported member 'ComponentPublicInstance'.`

@vue/composition-api 1.1.5
@vueuse/core @6.4.1(tried with 6.3.1 as well, same issue)
typescript @4.3.3

**Comment by Saranchenkov** [comment]
It happens because `vue-demi` exports all typings from `vue` package.
https://github.com/vueuse/vue-demi/blob/master/lib/index.d.ts#L15
Since it supports vue 2 and vue 3, which typings it exports depends on vue version you installed.
As result `@vueuse/core` imports type `ComponentPublicInstance` from `vue-demi`, but this type exists only in vue 3 https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/componentPublicInstance.ts#L169
So if you have vue 2 installed, your build will be broken

**Comment by dragomirweb** [comment]
> It happens because `vue-demi` exports all typings from `vue` package.
> https://github.com/vueuse/vue-demi/blob/master/lib/index.d.ts#L15
> Since it supports vue 2 and vue 3, which typings it exports depends on vue version you installed.
> As result `@vueuse/core` imports type `ComponentPublicInstance` from `vue-demi`, but this type exists only in vue 3 https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/componentPublicInstance.ts#L169
> So if you have vue 2 installed, your build will be broken

I agree, it is a vue-demi issue and vue-demi is a dep. of vueuse

**Comment by antfu** [comment]
Please upgrade `@vue/composition-api` to v1.2.1 which added this type.
