### ISSUE TITLE
bug: onclickoutside component @trigger not working

### ISSUE THREAD

**Issue by wouterkroes** [vueuse/vueuse#811]
Hello,

I have the feeling the `@trigger` of the [onclickoutside component](https://vueuse.org/core/onclickoutside/#component) is not working. The function version does work as expected.

I have created a example repo of the bug -> https://github.com/wouterkroes/onclickoutside-bug.
I have implemented both versions (function & component) of onclickoutside.
In the demo you can see that the `functionCount` updates as expected. But the `componentCount` does not.

Greetings,

Wouter

**Comment by wheatjs** [comment]
I don't see your implementations in that repo

**Comment by wouterkroes** [comment]
@wheatjs please refresh -> https://github.com/wouterkroes/onclickoutside-bug/blob/master/src/App.vue

**Comment by wyrd-code** [comment]
I am trying with Vue.js version 3.2.16 and 3.2.12 and for me, neither version works. Both throw the same error in console, shown below. 

Strangely enough, I have another project using 3.2.12 vue version and it works fine.

I'm not sure which way to go to investigate, but since there is a reproduction already available, I won't create another one. I will subscribe though, and if it's not the same issue if/when it gets fixed, I will create another issue.

```
Unhandled error during execution of native event handler 
...
runtime-dom.esm-bundler.js:1448 Uncaught TypeError: fn is not a function
    at runtime-dom.esm-bundler.js:1448
    at callWithErrorHandling (runtime-core.esm-bundler.js:6685)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:6694)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:347)
```

**Comment by wyrd-code** [comment]
Just to note, the issue I have seems unrelated to `vueuse` itself, I'm trying other components/directives and they too seem to have this issue.

**Comment by artmakarov** [comment]
Also `onClickOutside` does not work in Safari (desktop, mobile)
