### ISSUE TITLE
UseSessionStorage Not Working in Production Mode

### ISSUE THREAD

**Issue by loksoon** [vueuse/vueuse#865]
I have been try UseSessionStorage in method or @click is work in localhost,but in live production the UseSessionStorage in method is not working but the @click is work !!!!!!!!

Code (App.vue & State.js)
![123](https://user-images.githubusercontent.com/43371272/138257706-9d3aa8e9-ba7c-44c2-8502-3be726f585c2.jpg)

In Localhost
![local](https://user-images.githubusercontent.com/43371272/138257098-5f8f03e2-367e-4ce4-9a7f-dcda55857a0d.gif)

In Production Mode in a server
![live](https://user-images.githubusercontent.com/43371272/138257156-338a6136-bf7a-4458-b989-8f3e59ffcf9f.gif)

**Comment by wheatjs** [comment]
Thanks for the reproduction!

I can understand where the confusion comes from. `useSessionStoarge` returns a `ref`, not a `reactive` object. This mean when you are setting it in your script you will need to write `panelStage.value = value`. The reason it works in your template without using `.value` is due to ref unwrapping. [You can read more about it in the Vue Docs](https://v3.vuejs.org/guide/reactivity-fundamentals.html#ref-unwrapping)

To get your code working you can change your code to this

```html
<script setup>
import { panelState } from '@/state.js'
</script>

<script>
export default{
  data(){
    return{
      onclickMethod:'0'
    }
  },
  methods:{
    switchPanel(value){
      panelState.value = value
    }
  }
}
</script>

<template>
<div>
  <button @click="switchPanel('panel_1'),onclickMethod = '1'">Change Storage in Method (panel_1)</button>
  <button @click="switchPanel('panel_2'),onclickMethod = '2'">Change Storage in Method (panel_2)</button>
  <button @click="panelState = 'panel_3',onclickMethod = '3'">Change Storage in @Click (panel_3)</button>
  <button @click="panelState = 'panel_4',onclickMethod = '4'">Change Storage in @Click (panel_4)</button>

  
  <p>Method Clicked: {{onclickMethod}}</p>
  <p>Panel State: {{panelState}}</p>
</div>
</template>

```
